CREATE TABLE document_tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id VARCHAR(64) NOT NULL,
    tag VARCHAR(128) NOT NULL,
    tag_norm VARCHAR(128) NOT NULL,
    CONSTRAINT document_tags_document_fk FOREIGN KEY (document_id) REFERENCES documents(id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX document_tags_doc_norm_uq
    ON document_tags (document_id, tag_norm);

CREATE INDEX document_tags_tag_norm_idx
    ON document_tags (tag_norm);

INSERT INTO document_tags (document_id, tag, tag_norm)
WITH RECURSIVE split(document_id, rest, token) AS (
    SELECT id, COALESCE(tags, '') || ',', ''
    FROM documents
    UNION ALL
    SELECT document_id,
           SUBSTRING(rest, LOCATE(',', rest) + 1),
           TRIM(SUBSTRING(rest, 1, LOCATE(',', rest) - 1))
    FROM split
    WHERE rest <> '' AND LOCATE(',', rest) > 0
)
SELECT document_id,
       token,
       LOWER(token)
FROM split
WHERE token <> '';

ALTER TABLE documents
    DROP COLUMN tags;
